name: test form name
description: File a bug report v2
title: "[Bug]: "
labels: 
  - bug
  - triage
assignees:
  - testswell
body:
  - type: markdown
    attributes:
      value: |
        This can be the instruction for the user on how to use this form!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: bug_description
    attributes:
      label: Bug Description
      description: Describe the bug
      placeholder: Try to be as precise as possible
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: Version
      description: Which part of the platform is this?
      options:
        - dashboard
        - backend API
        - frontend API
        - payments
        - infrastructure
        - developer community
        - storefront
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: How important is this to your implementation?
      multiple: false
      options:
        - High
        - Medium
        - Low
    validations:
      required: true
videourl:
- type: input
    id: video_url
    attributes:
      label: Video URL
      description: Please add a video recording to help our team quickly identify the issue.
      placeholder: ex. youtube.com
    validations:
      required: false
